name: surrealdb
description: SurrealDB client written in pure dart. Auto reconnect, Typed functions
version: 0.8.0
repository: https://github.com/duhanbalci/surrealdb_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  uuid: ^4.3.3
  web_socket_channel: ^2.4.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  very_good_analysis: ^5.1.0
